# Generated by Django 5.2.11 on 2026-03-25 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructor', models.CharField(blank=True, default='Admin', max_length=100)),
                ('category', models.CharField(blank=True, choices=[('Programming', 'Programming'), ('AI', 'AI'), ('Web', 'Web'), ('Data Science', 'Data Science'), ('Design', 'Design'), ('Business', 'Business')], max_length=50, null=True)),
                ('level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi')], max_length=20, null=True)),
                ('duration', models.CharField(blank=True, default='4 weeks', max_length=50)),
                ('total_lectures', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.FloatField(blank=True, default=4.5, null=True)),
                ('students_enrolled', models.IntegerField(blank=True, default=0, null=True)),
                ('certificate', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('preview_video', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
