# Generated by Django 5.2.11 on 2026-03-30 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.PositiveIntegerField(default=5, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('course', 'order')},
        ),
    ]
