# Generated by Django 5.2.11 on 2026-03-30 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lecture_created_at_alter_lecture_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
