# Generated by Django 5.2.11 on 2026-04-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Required for recruiters', max_length=200, null=True),
        ),
    ]
