# Generated by Django 5.2.11 on 2026-03-19 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_internshipapplication_resume_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internship',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='internshipapplication',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterField(
            model_name='internship',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_internships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.internship'),
        ),
        migrations.AlterUniqueTogether(
            name='internshipapplication',
            unique_together={('internship', 'applicant')},
        ),
    ]
