# Generated by Django 5.2.11 on 2026-04-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_alter_internship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
    ]
