# Generated by Django 5.2.11 on 2026-03-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Offered', 'Offered'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
    ]
