# Generated by Django 4.2.30 on 2026-04-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_deadline_job_posted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
