# Generated by Django 4.2.30 on 2026-04-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobapplication_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
